export const menuTreeData =[
    {
        name:'Expenditure',
        path:'/expenditure',
        icon:"menu",
        children:[
            {
                name:'OwnManpower',
                path:"/expenditure/own-manpower",
                icon:"Tickets",
            },
            {
                name:'OutsourcedManpower',
                path:"/expenditure/outsourced-manpower",
                icon:"Tickets",
            },
        ]
    },
    {
        name:'Budget',
        path:'/budget',
        icon:"menu",
        children:[
            {
                name:'DeptBudget',
                path:"/budget/dept-budget",
                icon:"Tickets",
            },
            {
                name:'ProjectBudget',
                path:"/budget/project-budget",
                icon:"Tickets",
            },
        ]
    },
    {
        name:'Basic',
        path:'/basic',
        icon:"menu",
        children:[
            {
                name:'BussinessList',
                path:"/basic/bussiness-list",
                icon:"Tickets",
            },
            {
                name:'ProjectList',
                path:"/basic/project-list",
                icon:"Tickets",
            },
        ]
    },
]